credentials:
  usernames:
    ecom.juliette@gmail.com:
      email: ecom.juliette@gmail.com
      name: Juliette
      password: $2a$12$b37ETOS80sbmuXyZZ2Wr1.vgQQ3fvvZZGbXtgMSpRdw2kBXbCMWaa
      role: admin
cookie:
  name: authenticator
  key: some_secret_key
  expiry_days: 30
