credentials:
  usernames:
    ecom.juliette@gmail.com:
      email: ecom.juliette@gmail.com
      name: Juliette
      password: etteiluj1991
cookie:
  name: authenticator
  key: some_secret_key
  expiry_days: 30
