
credentials:
  usernames:
    juliette:
      email: ecom.juliette@gmail.com
      name: Juliette
      password: pbkdf2:sha256:260000$3Mjrhm57jYZMiXhn$9ae5803b9a21c6e04f250d554efbbd101d8a66e43df68e8e9b3c1ac9ad5cbf4b

cookie:
  expiry_days: 3
  key: automatch_cookie_secret_key
  name: auth_cookie

preauthorized:
  emails:
    - ecom.juliette@gmail.com
